server:
  port: 8080

spring:
  application:
    name: service-consumer
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 30
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      slowCallConfig:
        failureRateThreshold: 50
        slowCallRateThreshold: 30
        slowCallDurationThreshold: 2s
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      circuitBreakerA:
        baseConfig: default
      circuitBreakerB:
        baseConfig: slowCallConfig
  bulkhead:
    instances:
      defaultBulkhead:
        maxConcurrentCalls: 10
        maxWaitDuration: 20ms
  ratelimiter:
    instances:
      defaultRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 2s
        timeoutDuration: 0s 